// Extracts the game's real geography into world.js so chart.html can run from file://.
// Usage: node make-world.js [path-to-game-data]   (default: repository-local data/)
const fs = require('fs');
const path = require('path');
const dataDir = path.resolve(process.argv[2] || path.join(__dirname, '..', '..', 'data'));
const read = (f) => JSON.parse(fs.readFileSync(path.join(dataDir, f), 'utf8'));

const cities = read('cities.json').cities.map(c => ({
  id: c.id, name: c.name, region: c.region, lon: c.lon, lat: c.lat,
  pop: c.stats.population, industries: c.industries, governor: c.governor || null,
}));
const routes = read('routes.json').routes;
const terrain = {};
for (const t of read('terrain.json').terrain) terrain[t.id] = t;
const map = read('map.json');
const trucks = read('trucks.json').trucks;
const config = read('config.json');

const world = {
  cities, routes, terrain,
  map: { cellKm: map.cellKm, originLon: map.originLon, originLat: map.originLat,
         width: map.width, height: map.height, defaultBiome: map.defaultBiome,
         offRoad: map.offRoad, regions: map.regions },
  truck: trucks.find(t => t.id === config.startTruckIds[0]),
  startCityId: config.startCityId,
  startCash: config.startCash,
  roadDetourFactor: config.economy.roadDetourFactor,
};
fs.writeFileSync(path.join(__dirname, 'world.js'),
  '// GENERATED by make-world.js from repository-local data/ — do not hand-edit.\nwindow.WORLD = ' +
  JSON.stringify(world) + ';\n');
console.log(`world.js: ${cities.length} cities, ${routes.length} roads, ${map.regions.length} regions`);
