namespace MechaTrader.Core.Model;

/// <summary>A tradeable commodity. Content, loaded from goods.json.</summary>
public sealed class GoodDef
{
    public string Id { get; init; } = "";
    public string Name { get; init; } = "";
    public string Tier { get; init; } = "raw";
    public double BasePrice { get; init; }
    public double UnitVolume { get; init; } = 1.0;

    /// <summary>How hard price reacts to scarcity. Higher = more volatile.</summary>
    public double Elasticity { get; init; } = 0.6;
}

/// <summary>Road type on a route edge. Content, loaded from terrain.json.</summary>
public sealed class TerrainDef
{
    public string Id { get; init; } = "";
    public string Name { get; init; } = "";
    public double SpeedMultiplier { get; init; } = 1.0;
    public double CostMultiplier { get; init; } = 1.0;
}

/// <summary>A haulage vehicle type. Content, loaded from trucks.json.</summary>
public sealed class TruckDef
{
    public string Id { get; init; } = "";
    public string Name { get; init; } = "";
    public double Capacity { get; init; }
    public double SpeedKmPerDay { get; init; }
    public double UpkeepPerDay { get; init; }
    public double FuelPerKm { get; init; }
    public long Price { get; init; }
}

/// <summary>
/// An industry archetype. A city's whole market is generated by summing the
/// archetypes it declares, so adding a city is a few lines of data, not a table.
/// </summary>
public sealed class IndustryDef
{
    public string Id { get; init; } = "";
    public string Name { get; init; } = "";
    public Dictionary<string, double> Production { get; init; } = new();
    public Dictionary<string, double> Consumption { get; init; } = new();
}

public sealed class EconomyConfig
{
    /// <summary>Pull toward equilibrium per day, representing trade with the outside world.</summary>
    public double DriftRate { get; init; } = 0.25;

    /// <summary>Equilibrium stock = this many days of total throughput.</summary>
    public double EquilibriumDays { get; init; } = 10.0;

    public double MinEquilibrium { get; init; } = 40.0;
    public double MinStock { get; init; } = 5.0;
    public double NoiseSigma { get; init; } = 0.02;

    /// <summary>Buy/sell margin taken by the market, so you cannot round-trip in place.</summary>
    public double Spread { get; init; } = 0.06;

    public double MinPriceMult { get; init; } = 0.4;
    public double MaxPriceMult { get; init; } = 2.5;

    /// <summary>Roads are not straight lines; scales great-circle distance up.</summary>
    public double RoadDetourFactor { get; init; } = 1.25;

    /// <summary>
    /// Share of a city's intake that reaches its shelf each day. Lower means goods sold
    /// into a city take longer to come back onto the market.
    /// </summary>
    public double RestockRate { get; init; } = 0.35;
}

public sealed class GameConfig
{
    public long StartCash { get; init; } = 20000;
    public string StartCityId { get; init; } = "";
    public List<string> StartTruckIds { get; init; } = new();
    public EconomyConfig Economy { get; init; } = new();
}

/// <summary>
/// The levers a crew skill is allowed to pull. A skill declares one of these in
/// content; the simulation reads the lever rather than the skill id, so renaming or
/// retuning a skill is a data change and adding one that does nothing yet is legal.
/// </summary>
public static class CrewLever
{
    public const string Speed = "speed";
    public const string Buy = "buy";
    public const string Sell = "sell";
    public const string Upkeep = "upkeep";
    public const string None = "none";

    public static readonly IReadOnlyList<string> All = new[] { Speed, Buy, Sell, Upkeep, None };
}

/// <summary>
/// One crew ability. <see cref="MaxEffect"/> is what the lever gives at <c>maxSkill</c>
/// and scales linearly below it; its meaning depends on the lever:
/// speed = fractional speed bonus, buy/sell = share of the market spread erased,
/// upkeep = share of running costs cut.
/// </summary>
public sealed class CrewSkillDef
{
    public string Id { get; init; } = "";
    public string Name { get; init; } = "";
    public string Lever { get; init; } = CrewLever.None;
    public double MaxEffect { get; init; }
    public string Blurb { get; init; } = "";
}

/// <summary>A hiring archetype. <see cref="Primary"/> is the skill it rolls high in.</summary>
public sealed class CrewRoleDef
{
    public string Id { get; init; } = "";
    public string Name { get; init; } = "";

    /// <summary>Skill id this role specialises in; empty means a generalist.</summary>
    public string Primary { get; init; } = "";
}

public sealed class CrewWageDef
{
    public long Base { get; init; } = 5;
    public long PerSkillPoint { get; init; } = 6;
}

/// <summary>Shape of a city's recruitment pool.</summary>
public sealed class CandidateGenDef
{
    public int BasePerCity { get; init; } = 1;
    public double PerPopulation { get; init; } = 2.0;
    public int MaxPerCity { get; init; } = 5;
    public int PrimaryMin { get; init; } = 5;
    public int PrimaryMax { get; init; } = 10;
    public int SecondaryMin { get; init; } = 1;
    public int SecondaryMax { get; init; } = 5;
}

/// <summary>Everything about crew that is content. Loaded from crew.json.</summary>
public sealed class CrewConfig
{
    public int MaxSkill { get; init; } = 10;

    /// <summary>How many people the convoy can carry on the books at once.</summary>
    public int CrewCapacity { get; init; } = 4;

    /// <summary>A city's recruitment pool re-rolls this often.</summary>
    public int RefreshDays { get; init; } = 10;

    /// <summary>Signing fee, expressed as a multiple of the daily wage.</summary>
    public int SigningFeeDays { get; init; } = 20;

    /// <summary>Severance on dismissal, expressed as a multiple of the daily wage.</summary>
    public int SeveranceDays { get; init; } = 5;

    public CrewWageDef Wage { get; init; } = new();
    public CandidateGenDef Candidates { get; init; } = new();

    public List<CrewSkillDef> Skills { get; init; } = new();
    public List<CrewRoleDef> Roles { get; init; } = new();

    /// <summary>industryId to skillId to bonus points, applied to that city's candidates.</summary>
    public Dictionary<string, Dictionary<string, int>> IndustryAffinity { get; init; } = new();

    public List<string> FirstNames { get; init; } = new();
    public List<string> Surnames { get; init; } = new();

    /// <summary>The skill wired to a given lever, or null if content declares none.</summary>
    public CrewSkillDef? SkillFor(string lever)
    {
        foreach (var skill in Skills)
        {
            if (skill.Lever == lever) return skill;
        }
        return null;
    }
}
