namespace MechaTrader.Core.Model;

/// <summary>A tradeable commodity. Content, loaded from goods.json.</summary>
public sealed class GoodDef
{
    public string Id { get; init; } = "";
    public string Name { get; init; } = "";
    public string Tier { get; init; } = "raw";
    public double BasePrice { get; init; }
    public double UnitVolume { get; init; } = 1.0;

    /// <summary>How hard price reacts to scarcity. Higher = more volatile.</summary>
    public double Elasticity { get; init; } = 0.6;
}

/// <summary>Road type on a route edge. Content, loaded from terrain.json.</summary>
public sealed class TerrainDef
{
    public string Id { get; init; } = "";
    public string Name { get; init; } = "";
    public double SpeedMultiplier { get; init; } = 1.0;
    public double CostMultiplier { get; init; } = 1.0;
}

/// <summary>A haulage vehicle type. Content, loaded from trucks.json.</summary>
public sealed class TruckDef
{
    public string Id { get; init; } = "";
    public string Name { get; init; } = "";
    public double Capacity { get; init; }
    public double SpeedKmPerDay { get; init; }
    public double UpkeepPerDay { get; init; }
    public double FuelPerKm { get; init; }
    public long Price { get; init; }
}

/// <summary>
/// An industry archetype. A city's whole market is generated by summing the
/// archetypes it declares, so adding a city is a few lines of data, not a table.
/// </summary>
public sealed class IndustryDef
{
    public string Id { get; init; } = "";
    public string Name { get; init; } = "";
    public Dictionary<string, double> Production { get; init; } = new();
    public Dictionary<string, double> Consumption { get; init; } = new();
}

public sealed class EconomyConfig
{
    /// <summary>Pull toward equilibrium per day, representing trade with the outside world.</summary>
    public double DriftRate { get; init; } = 0.25;

    /// <summary>Equilibrium stock = this many days of total throughput.</summary>
    public double EquilibriumDays { get; init; } = 10.0;

    public double MinEquilibrium { get; init; } = 40.0;
    public double MinStock { get; init; } = 5.0;
    public double NoiseSigma { get; init; } = 0.02;

    /// <summary>Buy/sell margin taken by the market, so you cannot round-trip in place.</summary>
    public double Spread { get; init; } = 0.06;

    public double MinPriceMult { get; init; } = 0.4;
    public double MaxPriceMult { get; init; } = 2.5;

    /// <summary>Roads are not straight lines; scales great-circle distance up.</summary>
    public double RoadDetourFactor { get; init; } = 1.25;
}

public sealed class GameConfig
{
    public long StartCash { get; init; } = 20000;
    public string StartCityId { get; init; } = "";
    public List<string> StartTruckIds { get; init; } = new();
    public EconomyConfig Economy { get; init; } = new();
}
