namespace MechaTrader.Core.Model;

/// <summary>
/// An industry archetype. A city's whole market is generated by summing the
/// archetypes it declares, so adding a city is a few lines of data, not a table.
/// </summary>
public sealed class IndustryDef
{
    public string Id { get; init; } = "";
    public string Name { get; init; } = "";
    public Dictionary<string, double> Production { get; init; } = new();
    public Dictionary<string, double> Consumption { get; init; } = new();
}
