<#
    Codemap generator (Phase E, MIGRATION_PLAN.md Phase E step 3).

    Generates docs\codemap.md from repository facts: solution projects, C# files
    with line counts, the frontend inventory, tests, content data, tools, and root
    documents. The output is deterministic for a given tree (no wall-clock data;
    it records the commit it was generated at).

    Regenerate after any structural change (files added/moved/split, projects
    changed) - required after Phase D and Phase F complete (D-055). Never
    hand-edit docs\codemap.md.

    Usage:  powershell -NoProfile -ExecutionPolicy Bypass -File tools\Generate-Codemap.ps1
    Exit 0 when the codemap was written, else 1.
#>

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

$outPath = Join-Path $root 'docs\codemap.md'

function Get-LineCount([string]$path) {
    return [IO.File]::ReadAllLines($path).Count
}

function Format-Kb([long]$bytes) {
    return ('{0:N0} KB' -f [math]::Round($bytes / 1KB))
}

$commit = 'unknown'
try { $commit = (& git rev-parse HEAD).Trim() } catch { }

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('# Code map (generated)')
$lines.Add('')
$lines.Add("Generated by ``tools/Generate-Codemap.ps1`` from repository facts at commit ``$commit``.")
$lines.Add('Do not hand-edit: regenerate after structural changes (required after Phase D')
$lines.Add('and Phase F complete, per the process-streamlining revision `D-055`). For what')
$lines.Add('each area OWNS, see `docs/ownership.json`; for orientation, `docs/agents.md`.')
$lines.Add('')

# ---------------- solution projects ----------------
$lines.Add('## Solution projects')
$lines.Add('')
$lines.Add('| Project | Path | C# files | C# lines |')
$lines.Add('|---|---|---|---|')
$projects = @(Get-ChildItem -Path $root -Recurse -Filter '*.csproj' |
    Where-Object { $_.FullName -notmatch '\\(bin|obj|node_modules)\\' } |
    Sort-Object FullName)
foreach ($proj in $projects) {
    $projDir = $proj.DirectoryName
    $csFiles = @(Get-ChildItem -Path $projDir -Filter '*.cs' -File | Sort-Object Name)
    $csLines = 0
    foreach ($f in $csFiles) { $csLines += Get-LineCount $f.FullName }
    $rel = $proj.FullName.Substring($root.Length + 1)
    $lines.Add(('| {0} | {1} | {2} | {3:N0} |' -f $proj.BaseName, $rel, $csFiles.Count, $csLines))
}
$lines.Add('')

# ---------------- C# sources per project ----------------
foreach ($proj in $projects) {
    $projDir = $proj.DirectoryName
    $relProj = $proj.Directory.FullName.Substring($root.Length + 1)
    $csFiles = @(Get-ChildItem -Path $projDir -Filter '*.cs' -File -Recurse | Sort-Object FullName)
    if ($csFiles.Count -eq 0) { continue }
    $lines.Add("## $relProj")
    $lines.Add('')
    $lines.Add('| File | Lines |')
    $lines.Add('|---|---|')
    foreach ($f in $csFiles) {
        $rel = $f.FullName.Substring($projDir.Length + 1)
        $lines.Add(('| {0} | {1:N0} |' -f $rel, (Get-LineCount $f.FullName)))
    }
    $lines.Add('')
}

# ---------------- frontend ----------------
$chartDir = Join-Path $root 'web\chart'
$lines.Add('## Frontend (web/chart, served at /chart/)')
$lines.Add('')
$lines.Add('| File | Size |')
$lines.Add('|---|---|')
$chartFiles = @(Get-ChildItem -Path $chartDir -File | Sort-Object Name)
foreach ($f in $chartFiles) {
    $lines.Add(('| {0} | {1} |' -f $f.Name, (Format-Kb $f.Length)))
}
$artFiles = @(Get-ChildItem -Path (Join-Path $chartDir 'art') -Recurse -File -ErrorAction SilentlyContinue)
$artBytes = ($artFiles | Measure-Object Length -Sum).Sum
$lines.Add(('| art/ ({0} files) | {1} |' -f $artFiles.Count, (Format-Kb $artBytes)))
$lines.Add('')
$lines.Add('`world.js` is GENERATED from `data/` by `make-world.js` and pinned by')
$lines.Add('`tools/verify-worldjs.ps1`; `chart.html` (inline styles/scripts), `game-bridge.js`,')
$lines.Add('`ops.js`, `ops.css` and the tile worker are the Phase D extraction surface.')
$lines.Add('')

# ---------------- tests ----------------
$lines.Add('## Tests')
$lines.Add('')
$lines.Add('| Path | Size |')
$lines.Add('|---|---|')
$testFiles = @(Get-ChildItem -Path (Join-Path $root 'tests\MechaTrader.Core.Tests') -File -Filter '*.cs' | Sort-Object Name)
foreach ($f in $testFiles) { $lines.Add(('| tests/MechaTrader.Core.Tests/{0} | {1} |' -f $f.Name, (Format-Kb $f.Length))) }
$fixtures = @(Get-ChildItem -Path (Join-Path $root 'tests\MechaTrader.Core.Tests\Fixtures') -Recurse -File -ErrorAction SilentlyContinue)
$lines.Add(('| tests/MechaTrader.Core.Tests/Fixtures/ ({0} files) | (pinned determinism/save fixtures) |' -f $fixtures.Count))
$apiFixtures = @(Get-ChildItem -Path (Join-Path $root 'tests\api-fixtures') -File | Sort-Object Name)
foreach ($f in $apiFixtures) { $lines.Add(('| tests/api-fixtures/{0} | {1} |' -f $f.Name, (Format-Kb $f.Length))) }
$browserFiles = @(Get-ChildItem -Path (Join-Path $root 'tests\browser') -File | Where-Object { $_.Name -ne 'package-lock.json' } | Sort-Object Name)
foreach ($f in $browserFiles) { $lines.Add(('| tests/browser/{0} | {1} |' -f $f.Name, (Format-Kb $f.Length))) }
$lines.Add('')

# ---------------- data ----------------
$lines.Add('## Content data (data/, the only source of game content)')
$lines.Add('')
$lines.Add('| File | Size |')
$lines.Add('|---|---|')
$dataFiles = @(Get-ChildItem -Path (Join-Path $root 'data') -File -Filter '*.json' | Sort-Object Name)
foreach ($f in $dataFiles) { $lines.Add(('| data/{0} | {1} |' -f $f.Name, (Format-Kb $f.Length))) }
$lines.Add('')

# ---------------- tools and scripts ----------------
$lines.Add('## Tools and verification scripts')
$lines.Add('')
$lines.Add('| Path | Lines | Purpose (first comment line) |')
$lines.Add('|---|---|---|')
$scriptFiles = @(Get-ChildItem -Path (Join-Path $root 'tools') -File -Filter '*.ps1' | Sort-Object Name)
foreach ($f in $scriptFiles) {
    $purpose = ''
    foreach ($l in ([IO.File]::ReadAllLines($f.FullName))) {
        if ($l -match '^\s*(#{1,2})\s*(.+)$') { $purpose = $Matches[2].Trim(); break }
    }
    $rel = 'tools/' + $f.Name
    $lines.Add(('| {0} | {1:N0} | {2} |' -f $rel, (Get-LineCount $f.FullName), $purpose))
}
$rootScripts = @('check.ps1', 'play.ps1', 'install-launcher.ps1')
foreach ($name in $rootScripts) {
    $p = Join-Path $root $name
    if (Test-Path $p) {
        $purpose = ''
        foreach ($l in ([IO.File]::ReadAllLines($p))) {
            if ($l -match '^\s*(#{1,2})\s*(.+)$') { $purpose = $Matches[2].Trim(); break }
        }
        $lines.Add(('| {0} | {1:N0} | {2} |' -f $name, (Get-LineCount $p), $purpose))
    }
}
$lines.Add('')

# ---------------- docs ----------------
$lines.Add('## Agent-facing documentation (docs/)')
$lines.Add('')
$docsDir = Join-Path $root 'docs'
$docFiles = @(Get-ChildItem -Path $docsDir -Recurse -File -ErrorAction SilentlyContinue |
    Where-Object { $_.FullName -ne $outPath } | Sort-Object FullName)
$lines.Add('| Path |')
$lines.Add('|---|')
foreach ($f in $docFiles) {
    $rel = $f.FullName.Substring($root.Length + 1).Replace('\', '/')
    $lines.Add(('| {0} |' -f $rel))
}
$lines.Add('')

[IO.File]::WriteAllLines($outPath, $lines)
Write-Host "codemap written: $outPath ($($lines.Count) lines, commit $commit)"
exit 0
