<#
    Phase A step 6 (MIGRATION_LEDGER.md): F_worldjs.

    world.js is generated by D:\FrontMission-MapLab\make-world.js from this repository's
    data/ directory, but the script always writes its output beside itself
    (`path.join(__dirname, 'world.js')`) rather than to a caller-supplied path. So this
    copies make-world.js into an isolated temp directory and runs it FROM THERE, which
    makes __dirname the temp directory and leaves the live, checked-in world.js
    untouched. Line 1 of the output is a `// GENERATED ... from <dataDir>` comment that
    literally embeds the invocation path, so it always differs when this check runs from
    anywhere other than the exact path world.js was last generated from (a worktree,
    say) even when the actual content is identical; the comparison below hashes
    everything AFTER that first line, not the whole file. A real mismatch there means
    world.js is stale relative to data/, exactly the drift PA-KIMI-01 flagged as
    invisible today (play.ps1 regenerates on every launch and silently continues if it
    can't, so nothing currently catches this before the browser serves a stale map).

    Usage:  .\tools\verify-worldjs.ps1
    Exit 0 on match, 1 on mismatch or any failure.
#>

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$dataDir = Join-Path $repoRoot 'data'

function Fail($message) {
    Write-Host "FAIL  $message" -ForegroundColor Red
    exit 1
}

# Walk up looking for a 'FrontMission-MapLab' sibling, exactly like
# play.ps1::Update-ChartData and Program.cs::LocateMapLab — a worktree checkout does not
# necessarily sit one level below where the real sibling folder lives.
$mapLab = $null
$dir = (Get-Item $repoRoot).Parent
while ($dir -and -not $mapLab) {
    $candidate = Join-Path $dir.FullName 'FrontMission-MapLab'
    if (Test-Path (Join-Path $candidate 'make-world.js')) { $mapLab = $candidate }
    $dir = $dir.Parent
}
if (-not $mapLab) {
    # The expected pre-migration state for a clean/isolated clone (Phase A step 7):
    # with no sibling MapLab reachable, play.ps1 itself skips regeneration rather than
    # failing (`Update-ChartData`'s "chart data left as-is" branch), and /chart/ is
    # expected to 404 there too. This is not the drift the gate exists to catch — it
    # would fail identically on Phase A's own current two-folder layout by design.
    Write-Host 'SKIP  no FrontMission-MapLab sibling reachable above this checkout (expected in an isolated clone)' -ForegroundColor DarkGray
    exit 0
}

$makeWorld = Join-Path $mapLab 'make-world.js'
$liveWorldJs = Join-Path $mapLab 'world.js'

if (-not (Test-Path $makeWorld)) { Fail "make-world.js not found at $makeWorld" }
if (-not (Test-Path $liveWorldJs)) { Fail "live world.js not found at $liveWorldJs" }
if (-not (Get-Command node -ErrorAction SilentlyContinue)) { Fail 'node not found on PATH' }

$temp = Join-Path $env:TEMP ("verify-worldjs-" + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $temp | Out-Null

try {
    Copy-Item $makeWorld (Join-Path $temp 'make-world.js')

    Push-Location $temp
    try {
        $output = & node 'make-world.js' $dataDir 2>&1 | Out-String
        $exitCode = $LASTEXITCODE
    }
    finally {
        Pop-Location
    }

    if ($exitCode -ne 0) { Fail "node exited $exitCode`n$output" }

    $regenerated = Join-Path $temp 'world.js'
    if (-not (Test-Path $regenerated)) { Fail "make-world.js ran but produced no world.js`n$output" }

    # Skip line 1 (the `// GENERATED ... from <dataDir>` provenance comment) on both
    # sides before hashing, so this compares only the substantive `window.WORLD = ...`
    # payload and is insensitive to which absolute path invoked the generator. Written
    # to temp files so Windows PowerShell 5.1's Get-FileHash (no Convert.ToHexString
    # there) can do the hashing.
    $regeneratedBody = (Get-Content $regenerated -Raw) -split "`n", 2 | Select-Object -Last 1
    $liveBody = (Get-Content $liveWorldJs -Raw) -split "`n", 2 | Select-Object -Last 1

    $regeneratedBodyFile = Join-Path $temp 'regenerated-body.txt'
    $liveBodyFile = Join-Path $temp 'live-body.txt'
    [IO.File]::WriteAllText($regeneratedBodyFile, $regeneratedBody, [Text.Encoding]::UTF8)
    [IO.File]::WriteAllText($liveBodyFile, $liveBody, [Text.Encoding]::UTF8)

    $regeneratedHash = (Get-FileHash $regeneratedBodyFile -Algorithm SHA256).Hash
    $liveHash = (Get-FileHash $liveBodyFile -Algorithm SHA256).Hash

    if ($regeneratedHash -ne $liveHash) {
        Fail ("world.js is stale relative to data/ (payload hash live $liveHash, regenerated $regeneratedHash)`n" +
              "Run: node `"$makeWorld`" `"$dataDir`"  (from $mapLab) to refresh it.")
    }

    Write-Host "PASS  world.js matches data/ (payload hash $liveHash)" -ForegroundColor Green
    Write-Host "      $output".TrimEnd() -ForegroundColor DarkGray
    exit 0
}
finally {
    Remove-Item -Recurse -Force $temp -ErrorAction SilentlyContinue
}
