<#
    Verify the repository-local world generator without mutating the checkout.

    The generator and its six inputs are copied into two isolated clone-shaped layouts.
    Each copy is run without an input argument and from outside web/chart/, proving that
    its default resolves repository-local data/ from the generator location. Both complete
    outputs must be byte-identical to each other and to web/chart/world.js.

    Usage:  .\tools\verify-worldjs.ps1
    Exit 0 on match, 1 on mismatch or any failure.
#>

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$generator = Join-Path $repoRoot 'web\chart\make-world.js'
$liveWorldJs = Join-Path $repoRoot 'web\chart\world.js'
$dataDir = Join-Path $repoRoot 'data'
$inputNames = @('cities.json', 'routes.json', 'terrain.json', 'map.json', 'trucks.json', 'config.json')
$expectedHeader = '// GENERATED by make-world.js from repository-local data/ ' + [char]0x2014 + ' do not hand-edit.'
$expectedPayloadSha256 = 'edd4be44b511907367cb8c2200cc262bf4fade959d48b66bc16dad1d9cd79f66'
$tempRoot = Join-Path ([IO.Path]::GetTempPath()) ('verify-worldjs-' + [guid]::NewGuid().ToString('N'))

function Get-Sha256([string]$path) {
    return (Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant()
}

function Get-BytesAfterFirstLf([string]$path) {
    [byte[]]$bytes = [IO.File]::ReadAllBytes($path)
    $lf = [Array]::IndexOf($bytes, [byte]10)
    if ($lf -lt 0) { throw "$path has no generated header line" }

    [byte[]]$payload = New-Object byte[] ($bytes.Length - $lf - 1)
    [Array]::Copy($bytes, $lf + 1, $payload, 0, $payload.Length)
    return $payload
}

function Get-BytesSha256([byte[]]$bytes) {
    $sha = [Security.Cryptography.SHA256]::Create()
    try {
        return -join ($sha.ComputeHash($bytes) | ForEach-Object { $_.ToString('x2') })
    }
    finally {
        $sha.Dispose()
    }
}

$sourcePaths = @($generator, $liveWorldJs)
foreach ($name in $inputNames) {
    $sourcePaths += Join-Path $dataDir $name
}

$beforeHashes = @{}
$failure = $null
$fullHash = $null

try {
    if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
        throw 'node not found on PATH'
    }

    foreach ($sourcePath in $sourcePaths) {
        if (-not (Test-Path -LiteralPath $sourcePath -PathType Leaf)) {
            throw "required source file not found: $sourcePath"
        }
        $beforeHashes[$sourcePath] = Get-Sha256 $sourcePath
    }

    $livePayloadHash = Get-BytesSha256 (Get-BytesAfterFirstLf $liveWorldJs)
    if ($livePayloadHash -ne $expectedPayloadSha256) {
        throw "WORLD payload changed from the PB-ROOT-01 green base (expected $expectedPayloadSha256, actual $livePayloadHash)"
    }

    $runRoots = @(
        (Join-Path $tempRoot 'clone-a'),
        (Join-Path $tempRoot 'different absolute clone b')
    )
    $generatedPaths = @()

    foreach ($runRoot in $runRoots) {
        $chartDir = Join-Path $runRoot 'web\chart'
        $runDataDir = Join-Path $runRoot 'data'
        $workingDir = Join-Path $runRoot 'run-from-here'
        New-Item -ItemType Directory -Path $chartDir, $runDataDir, $workingDir -Force | Out-Null

        Copy-Item -LiteralPath $generator -Destination (Join-Path $chartDir 'make-world.js')
        foreach ($name in $inputNames) {
            Copy-Item -LiteralPath (Join-Path $dataDir $name) -Destination (Join-Path $runDataDir $name)
        }

        Push-Location $workingDir
        try {
            $output = & node (Join-Path $chartDir 'make-world.js') 2>&1 | Out-String
            $exitCode = $LASTEXITCODE
        }
        finally {
            Pop-Location
        }

        if ($exitCode -ne 0) {
            throw "node exited $exitCode for $runRoot`n$output"
        }

        $generatedPath = Join-Path $chartDir 'world.js'
        if (-not (Test-Path -LiteralPath $generatedPath -PathType Leaf)) {
            throw "generator produced no world.js in $chartDir`n$output"
        }

        $header = [IO.File]::ReadLines($generatedPath) | Select-Object -First 1
        if ($header -ne $expectedHeader) {
            throw "generated header is not stable repository-relative provenance: $header"
        }

        $payloadHash = Get-BytesSha256 (Get-BytesAfterFirstLf $generatedPath)
        if ($payloadHash -ne $expectedPayloadSha256) {
            throw "generated WORLD payload changed from the PB-ROOT-01 green base (expected $expectedPayloadSha256, actual $payloadHash)"
        }

        $generatedPaths += $generatedPath
    }

    $runOneHash = Get-Sha256 $generatedPaths[0]
    $runTwoHash = Get-Sha256 $generatedPaths[1]
    $liveHash = Get-Sha256 $liveWorldJs
    if ($runOneHash -ne $runTwoHash) {
        throw "isolated generation is not deterministic (run 1 $runOneHash, run 2 $runTwoHash)"
    }
    if ($runOneHash -ne $liveHash) {
        throw "web/chart/world.js is stale (checked-in $liveHash, generated $runOneHash)"
    }

    $fullHash = $liveHash
}
catch {
    $failure = $_.Exception.Message
}
finally {
    foreach ($sourcePath in $beforeHashes.Keys) {
        if (-not (Test-Path -LiteralPath $sourcePath -PathType Leaf)) {
            if (-not $failure) { $failure = "verification removed source file: $sourcePath" }
            continue
        }

        $afterHash = Get-Sha256 $sourcePath
        if ($afterHash -ne $beforeHashes[$sourcePath] -and -not $failure) {
            $failure = "verification mutated source file: $sourcePath"
        }
    }

    if (Test-Path -LiteralPath $tempRoot) {
        Remove-Item -LiteralPath $tempRoot -Recurse -Force -ErrorAction SilentlyContinue
    }
}

if ($failure) {
    Write-Host "FAIL  $failure" -ForegroundColor Red
    exit 1
}

Write-Host "PASS  repository-local world.js is deterministic and source-immutable (SHA-256 $fullHash)" -ForegroundColor Green
exit 0
